server:
  port: 8001
 
spring:
  application:
    name: UniversityDepartment
  banner:
    image:
      location: classpath:banner.txt    
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/UniversitY
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    
management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: "*"
keycloak:
  auth-server-url: http://localhost:8080
  realm: UniversitY
  resource: UniversityStudent
  public-client: true