server:
  port: 8000
 
spring:
  application:
    name: UniversityStudent
  banner:
    image:
      location: classpath:banner.txt
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/UniversitY
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

keycloak:
  auth-server-url: http://localhost:8080
  realm: UniversitY
  resource: UniversityStudent
  public-client: true
