server:
  port: 8080
  
spring:
  application:
    name: UniversityStudent
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5433/UniversitY
    username: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


